# HEEDS|MDO 内で実行される、名前の事前チェック用テンプレートです。
# project_check がプレースホルダを埋めて一時ファイルとして書き出します。
# 解析は実行しません。このファイル自体は HEEDSMDO 外では動きません。

"""
__PLACEHOLDER_DOC__
Generated by heeds/project_check.py - do not edit by hand for a live run.
"""

import json
import os

import HEEDS

# --- injected by host ---
PROJECT_PATH = __PLACEHOLDER_PROJECT_PATH__
OUT_DIR = __PLACEHOLDER_OUT_DIR__
STUDIES = __PLACEHOLDER_STUDIES__
VARIABLE_NAMES = __PLACEHOLDER_VARIABLE_NAMES__
# --- end injected ---


def _heeds_path(path):
    return path.replace("\\\\", "/").replace("\\", "/")


def _item_names(parent, type_obj):
    names = []
    if parent is None:
        return names
    try:
        for item in parent.children(type_obj):
            try:
                name = item.name()
            except Exception:
                continue
            if name:
                names.append(str(name))
    except Exception as error:
        HEEDS.logMessage("children listing failed: %s" % error)
    return names


def _inspect_study(project, spec):
    study_id = spec.get("id")
    study_name = spec.get("heeds_name")

    result = {
        "id": study_id,
        "heeds_name": study_name,
        "found": False,
        "variables": {},
        "responses": {},
        "actual_variables": [],
        "actual_responses": [],
        "process_names": [],
        "errors": [],
    }

    study = project.findChild(study_name, HEEDS.Study)
    if study is None:
        result["errors"].append(
            "プログラムの Study 名 '%s' が HEEDS にない" % study_name
        )
        return result

    result["found"] = True

    for name in VARIABLE_NAMES:
        var = study.findVariable(name)
        result["variables"][name] = var is not None
        if var is None:
            result["errors"].append(
                "プログラムの入力変数 '%s' が HEEDS にない" % name
            )

    agent = None
    try:
        agent = study.searchAgent()
    except Exception as error:
        HEEDS.logMessage("searchAgent failed: %s" % error)

    if agent is not None:
        result["actual_variables"] = _item_names(agent, HEEDS.AgentVariable)
        result["actual_responses"] = _item_names(agent, HEEDS.AgentResponse)

    try:
        result["process_names"] = _item_names(study, HEEDS.Process)
    except Exception:
        result["process_names"] = []

    return result


def main():
    out_dir = _heeds_path(OUT_DIR)
    os.makedirs(out_dir, exist_ok=True)

    summary = {
        "ok": False,
        "project": PROJECT_PATH,
        "project_opened": False,
        "project_studies": [],
        "project_processes": [],
        "studies": [],
        "errors": [],
    }

    project_path = _heeds_path(PROJECT_PATH)
    project = HEEDS.open(project_path)
    if project is None:
        project = HEEDS.currentProject()
    if project is None:
        summary["errors"].append("Failed to open HEEDS project: %s" % project_path)
    else:
        summary["project_opened"] = True
        summary["project_studies"] = _item_names(project, HEEDS.Study)
        summary["project_processes"] = _item_names(project, HEEDS.Process)
        for spec in STUDIES:
            item = _inspect_study(project, spec)
            summary["studies"].append(item)
            summary["errors"].extend(
                ["%s (%s): %s" % (item.get("id"), item.get("heeds_name"), msg)
                 for msg in item.get("errors") or []]
            )

    summary["ok"] = bool(summary["project_opened"]) and not summary["errors"]

    summary_path = _heeds_path(os.path.join(out_dir, "heeds_check.json"))
    with open(summary_path, "w", encoding="utf-8") as file:
        json.dump(summary, file, ensure_ascii=False, indent=2)
    HEEDS.logMessage("heeds check wrote: %s" % summary_path)

    if not summary["ok"]:
        raise AssertionError("; ".join(summary["errors"]) or "heeds check failed")


if __name__ == "__main__":
    main()
