# HEEDS|MDO 内で実行される公式 Python API スクリプトのテンプレートです。
# cli_backend がプレースホルダを埋めて一時ファイルとして書き出します。
# このファイル自体は HEEDSMDO 外では動きません（import HEEDS 不可）。

"""
__PLACEHOLDER_DOC__
Generated by heeds/cli_backend.py - do not edit by hand for a live run.
"""

import json
import os

import HEEDS

# --- injected by host ---
PROJECT_PATH = __PLACEHOLDER_PROJECT_PATH__
OUT_DIR = __PLACEHOLDER_OUT_DIR__
STUDIES = __PLACEHOLDER_STUDIES__
VARIABLES = __PLACEHOLDER_VARIABLES__
LEVELS = __PLACEHOLDER_LEVELS__
# --- end injected ---


def _heeds_path(path: str) -> str:
    return path.replace("\\\\", "/").replace("\\", "/")


def _resolution(lower: float, upper: float, step: float) -> int:
    if step <= 0:
        return 2
    count = int(round((upper - lower) / step)) + 1
    return max(2, count)


def _jsonable(value):
    if value is None:
        return None
    if isinstance(value, (bool, int, float, str)):
        return value
    try:
        return float(value)
    except Exception:
        try:
            return str(value)
        except Exception:
            return None


def _apply_variables(study) -> None:
    for spec in VARIABLES:
        name = spec["name"]
        lower = float(spec["lower"])
        upper = float(spec["upper"])
        step = float(spec["step"])
        if spec.get("baseline") is None:
            baseline = (lower + upper) / 2.0
        else:
            baseline = float(spec["baseline"])
        resolution = _resolution(lower, upper, step)
        study_var = study.findVariable(name)
        if study_var is None:
            raise AssertionError("Variable not found in study: %s" % name)
        study_var.set(
            "min",
            lower,
            "baseline",
            baseline,
            "max",
            upper,
            "resolution",
            resolution,
        )


def _user_design_set(study):
    """EVAL 用の設計表を1つにします。残っていた表は空にして再利用します。"""
    existing = []
    try:
        found = study.children(HEEDS.UserDesignSet)
        if found:
            existing = list(found)
    except Exception as error:
        HEEDS.logMessage("UserDesignSet scan failed: %s" % error)
    if not existing:
        return study.createUserDesignSet("_chat_shared_levels")
    primary = existing[0]
    for extra in existing[1:]:
        try:
            extra.removeAll()
        except Exception as error:
            HEEDS.logMessage("UserDesignSet clear failed: %s" % error)
        try:
            HEEDS.removeItem(extra)
        except Exception as error:
            HEEDS.logMessage("UserDesignSet remove failed: %s" % error)
    return primary


def _assign_shared_levels(study) -> None:
    """全試験が同じ順・同じ入力になるよう、指定した設計だけを評価します。"""
    study.set("strAgentType", "EVAL")
    _apply_variables(study)
    design_set = _user_design_set(study)
    design_set.removeAll()
    params = {}
    for spec in VARIABLES:
        name = spec["name"]
        param = study.findVariable(name)
        if param is None:
            raise AssertionError("Variable not found in study: %s" % name)
        params[name] = param
    for index, level in enumerate(LEVELS, start=1):
        item_index = design_set.addItem()
        design_set.setValue(item_index, "name", "level_%d" % index)
        design_set.setValue(item_index, "useResp", False)
        design_set.setValue(item_index, "map", False)
        for name, param in params.items():
            design_set.setValue(item_index, param, level[name])
    design_set.mapVarsAllItems(False)


def _value_at(param, design_id):
    if param is None or design_id is None or int(design_id) <= 0:
        return None
    try:
        return _jsonable(param.valueAt(int(design_id)))
    except Exception:
        return None


def _list_response_params(study) -> dict:
    """Study にある AgentResponse を名前のまま集めます。"""
    found = {}
    try:
        agent = study.searchAgent()
    except Exception:
        agent = None
    if agent is None:
        return found
    try:
        for param in agent.children(HEEDS.AgentResponse):
            name = param.name()
            if name:
                found[str(name)] = param
    except Exception as error:
        HEEDS.logMessage("AgentResponse scan failed: %s" % error)
    return found


def _list_design_ids(study) -> list:
    """評価済みデザインの evaluation id（1始まり）を列挙する。"""
    ids = []
    try:
        design_set = study.createDesignSet(
            name="_chat_export_all",
            feasible=True,
            infeasible=True,
            success=True,
        )
        raw = design_set.designIds()
        if raw:
            ids = [int(item) for item in raw]
    except Exception as error:
        HEEDS.logMessage("createDesignSet failed: %s" % error)

    if ids:
        return sorted(set(ids))

    # フォールバック: best だけでも返す
    try:
        best_id = study.bestDesignId()
        if best_id is not None and int(best_id) > 0:
            return [int(best_id)]
    except Exception:
        pass
    return []


def _collect_designs(study) -> dict:
    input_params = {}
    for spec in VARIABLES:
        name = spec["name"]
        input_params[name] = study.findVariable(name)

    resolved = _list_response_params(study)
    response_params = resolved
    design_ids = _list_design_ids(study)

    designs = []
    for design_id in design_ids:
        inputs = {}
        for name, param in input_params.items():
            inputs[name] = _value_at(param, design_id)
        responses = {}
        for name, param in response_params.items():
            responses[name] = _value_at(param, design_id)
        designs.append(
            {
                "design_id": design_id,
                "inputs": inputs,
                "responses": responses,
            }
        )

    best_id = None
    try:
        best_id = study.bestDesignId()
    except Exception:
        best_id = None

    best_design = None
    for item in designs:
        if best_id is not None and int(item["design_id"]) == int(best_id):
            best_design = item
            break
    if best_design is None and designs:
        best_design = designs[0]

    return {
        "designs": designs,
        "best_design_id": best_id,
        "inputs_at_best": (best_design or {}).get("inputs") or {},
        "responses_at_best": (best_design or {}).get("responses") or {},
    }


def _run_one(project, study_id: str, study_name: str) -> dict:
    study = project.findChild(study_name, HEEDS.Study)
    if study is None:
        raise AssertionError("Study not found: %s" % study_name)

    if hasattr(HEEDS, "setCurrentStudy"):
        HEEDS.setCurrentStudy(study)
    else:
        project.setCurrentStudy(study)

    _apply_variables(study)
    _assign_shared_levels(study)
    study.unlock()
    ok = study.checkAndReport()
    if not ok:
        raise AssertionError("checkAndReport failed for study: %s" % study_name)

    started = study.run(results="reuse", wait=True)
    if not started:
        study.wait()

    status = study.status()
    if status != "completed":
        HEEDS.logMessage("Study %s status=%s; waiting..." % (study_name, status))
        study.wait()
        status = study.status()

    report_name = "%s_Report.txt" % study_id
    report_path = _heeds_path(os.path.join(OUT_DIR, report_name))
    study.writeReport(report_path)

    collected = _collect_designs(study)

    return {
        "id": study_id,
        "heeds_study_name": study_name,
        "status": status,
        "best_design_id": collected["best_design_id"],
        "report_path": report_path,
        "designs": collected["designs"],
        "inputs_at_best": collected["inputs_at_best"],
        "responses": collected["responses_at_best"],
    }


def main() -> None:
    out_dir = _heeds_path(OUT_DIR)
    os.makedirs(out_dir, exist_ok=True)

    project_path = _heeds_path(PROJECT_PATH)
    project = HEEDS.open(project_path)
    if project is None:
        project = HEEDS.currentProject()
    assert project is not None, "Failed to open HEEDS project: %s" % project_path

    results = []
    errors = []
    for item in STUDIES:
        study_id = item["id"]
        study_name = item["heeds_name"]
        try:
            results.append(_run_one(project, study_id, study_name))
        except Exception as error:
            errors.append("%s (%s): %s" % (study_id, study_name, error))
            HEEDS.logMessage(str(error))

    summary = {
        "ok": len(errors) == 0,
        "backend": "cli",
        "studies": results,
        "errors": errors,
    }
    summary_path = _heeds_path(os.path.join(out_dir, "heeds_summary.json"))
    with open(summary_path, "w", encoding="utf-8") as file:
        json.dump(summary, file, ensure_ascii=False, indent=2)

    if errors:
        raise AssertionError("; ".join(errors))


if __name__ == "__main__":
    main()
